### ISSUE TITLE
Layouting problem with ScrollingComposite on iOS

### ISSUE THREAD

**Issue by mkempka** [eclipsesource/tabris#278]
Example application: ECPM, can be tried on the review server
- Open the medic module
- Use a recent patient with a recent questionnaire
- Open the Questions tab
- Scroll down a bit
- Navigate to "Übersicht"
- Hit OPx Fragen (or any other filter on the "Ubersicht")
- Notice that the first question is now somewhere in the middle of the page
- Expected: The first question is at the top

Webclient and Android client behave as expected. Issue found on iOS 7.0.4

**Comment by ifurnadjiev** [comment]
Not reproducible with Tabris for Eclipse RAP 3.6
