### ISSUE TITLE
Add support for cloud push services

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris#351]
Tabris apps should be able to use cloud push services.

iOS: [APN (Apple Push Notification Service)](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html)
Android: [GCM (Google Cloud Messaging for Android)](http://developer.android.com/google/gcm/index.html)

**Comment by camstuart** [comment]
Would it be possible to reference more guides in http://developer.eclipsesource.com/tabris/docs/1.4/working/client-services/cloud-push/ ?

I have never worked with xcode, and from the above example really have no idea where to begin my journey
