### ISSUE TITLE
Markup in Label on Android not working

### ISSUE THREAD

**Issue by JohnGymer** [eclipsesource/tabris#355]
Markup does not appear to work on Android in a Label control.
Works ok on iOS.
(this is the label.setData(RWT.MARKUP_ENABLED, enabled); feature now in Tabris 1.4)

**Comment by mouaniss** [comment]
I confirm that behavior
If the HTML value is set before the shell is painted, the markup is not evaluated at all on Android.
To force that evaluation, the code has to be placed in a PaintListener (very bad idea)
shell.addPaintListener(new PaintListener() {
				@Override
				public void paintControl(PaintEvent event) {
					label.setText("regular <b>bold</b> <i>italic</i>");
				}});
On iOS, markup is working well as is supposed to be.
Any idea to have the same result even if the shell is not painted yet ?

**Comment by mpost** [comment]
@mouaniss What tabris version are you using?

**Comment by mouaniss** [comment]
Oh sorry, I didn't mentioned details about used platform 
Tabris 1.4.5 RAP 2.3.1 (with default android launcher and default gradle configuration)
Android 5.1 : Samsung Note 4
Android 4.4.4 : Samsung Note pro 12.2 
Android 4.2.2 : Asus Transformer PAD

**Comment by mpost** [comment]
@mouaniss Thanks for the detailed input. We will look into the issue.
