### ISSUE TITLE
 Android clients should send focus lost events

### ISSUE THREAD

**Issue by mkempka** [eclipsesource/tabris#386]
Text widgets on iOS support focusLost events. 
Text widgets on Android don't. 

To support the goal of tabris to write the code once for all platforms only, Android clients should send focus Lost events.

In terms of 'when' these events come, it should be in the same manner as on iOS.

**Comment by ifurnadjiev** [comment]
I think this is a dup of https://github.com/eclipsesource/tabris-android/issues/669

**Comment by mpost** [comment]
Closed via eclipsesource/tabris-android#669
