### ISSUE TITLE
Ampersand not displayed on iOS

### ISSUE THREAD

**Issue by evolanakis** [eclipsesource/tabris#387]
Button b = new Button(parent, SWT.PUSH);
b.setText("Foo && Bar"); 
// result: "Foo Bar", expected: "Foo & Bar"

**Comment by jordiboehmelopez** [comment]
I can't reproduce the problem. I created a couple of tests to check this use case - and they are green:

- (void)testOnPushButton {
    Button *button = [self newObjectWithId:@"t1" parent:nil properties:@{@"style":@[@"PUSH"]} andClient:nil ofClass:[Button class]];

    button.text = @"Foo && Bar";

    XCTAssertEqualObjects([button.button titleLabel].text, @"Foo & Bar");
}

- (void)testEscapedAmp {
    XCTAssertEqualObjects([Mnemonics removeMnemonics:@"Open && Close"], @"Open & Close");
}

**Comment by evolanakis** [comment]
```java
Shell s = new Shell(parent.getShell(), SWT.TITLE);
s.setText("Father && Son");
s.setBackground(s.getDisplay().getSystemColor(SWT.COLOR_GREEN));
s.setMaximized(true);
s.open();
```
