### ISSUE TITLE
Error in 'pause' listener

### ISSUE THREAD

**Issue by rherrmann** [eclipsesource/tabris#407]
My app has a _pause_ listener defined as follows:
```javascript
saveSettings = function() {
  localStorage.setItem( "foo", fooInput.get( "text" ) );
}
tabris.app.on( "pause", saveSettings );
```

`fooInput` is a TextInput that lives on the only top-level page. When the app is suspended and the text input wasn't touched before (i.e. nothing entered or otherwise interacted with) an error occurs. 
No message is shown, just an overlay with two curly braces that fades away after a while.
```
{   }
```

If the puase listener is removed, the error disappears also. If the `saveSettings` code is run outside the pause event, it executes just fine.

**Comment by jonek** [comment]
Is this a Tabris or a Tabris.js question?

**Comment by rherrmann** [comment]
Sorry, wrong issue tracker. I've opened https://github.com/eclipsesource/tabris-js/issues/445
