### ISSUE TITLE
PageOperator.open() does nothing on iOS under certain circumstances

### ISSUE THREAD

**Issue by rherrmann** [eclipsesource/tabris#411]
Create two pages, a top-level page and a regular page like so:
```java
PageConfiguration page1 = new PageConfiguration( "first-page-id", Page1.class );
page1.setTopLevel( true );
PageConfiguration page2 = new PageConfiguration( "second-page-id", Page2.class );
```
Within the selection listener of a button, the first page explicitly navigates to the second page like so:
```java
getUI().getPageOperator().openPage( "second-page-id" )
```

While this works as expected for the first time, it does not so after navigating back from the second page to the first page. There is no visual change whatsoever, the first page remains visible and intact.

This issue occurs on iOS clients only, Tabris Remote on Android works as expected.

**Comment by patrykmol** [comment]
Fix backported from https://github.com/eclipsesource/tabris-ios/issues/762
