### ISSUE TITLE
Support RAP 3.0/3.1

### ISSUE THREAD

**Issue by mferlan** [eclipsesource/tabris#413]
Any chance of adopting RAP 3.0 soon?

**Comment by gosia-eclipsesource** [comment]
RAP 3.0/3.1 will be supported as of the 1.5 release, which is planned for July 2016.

**Comment by davidleetw** [comment]
Deeply hope Tabris supports RAP 3.1 ASAP.
planned for July 2016. and what date to release?

**Comment by gosia-eclipsesource** [comment]
@davidleetw No concrete date yet, but we are targeting the first half of July.

**Comment by JohnGymer** [comment]
Any update on 1.5 release date?
Will it include RAP 3.0 or 3.1?
Thanks, John

**Comment by gosia-eclipsesource** [comment]
@JohnGymer Hi John. It will include RAP 3.1. There's been some delay but we are still targeting this month.

**Comment by JohnGymer** [comment]
So I guess RAP 3.1 didn't make it into Tabris 1.5 then?

**Comment by gosia-eclipsesource** [comment]
Yes, sorry about that. RAP 3.1 support is not ready to be published yet.

**Comment by gosia-eclipsesource** [comment]
RAP 3.x support is now complete.

**Comment by amedavid** [comment]
We can use RAP3.1 only with Java8?
Is there a possibility to use RAP3.0?

**Comment by ifurnadjiev** [comment]
RAP 3.x requires Java 7. Tabris 2.0 is compatible with both RAP 3.0 and 3.1.

**Comment by amedavid** [comment]
Okay but in the Documentation we read this:

> Minimum Requirements
> Move org.eclipse.rap.jface.databinding to Java 8
> 
> The underlying platform bundles org.eclipse.core.databinding.* now require Java 8. The Bundle-RequiredExecutionEnvironment (BREE) of "org.eclipse.rap.jface.databinding" bundle has been updated to JavaSE-1.8. 

So we can use in Tabris RAP3.1 with Java 7? 

In the Target we can't choose 3.0 see Picture: 
![2016-09-28_10h31_56](https://cloud.githubusercontent.com/assets/19856611/18906199/d4a2db88-8566-11e6-9fcf-f6e821d6009b.png)

**Comment by ifurnadjiev** [comment]
That's a requirement for org.eclipse.rap.jface.databinding (enforced by org.eclipse.core.databinding.*) bundle only. If you develop an application without databinding, running on Java 7 is fine.
