### ISSUE TITLE
Navigation Drawer

### ISSUE THREAD

**Issue by KathrinKieckbusch** [eclipsesource/tabris#435]
Hello, the link below describes a navigation drawer which is for Java Script. Is this also available for Java?
http://eclipsesource.com/blogs/2015/03/26/tabris-js-examples-drawer/

**Comment by mpost** [comment]
The navigation drawer is also available for tabris when you have multiple top level pages in the tabris UI.

See http://developer.eclipsesource.com/tabris/docs/1.4/working/tabris-ui/
