### ISSUE TITLE
ClientDialog should allow to set the canceled-on-touch-outside property

### ISSUE THREAD

**Issue by evolanakis** [eclipsesource/tabris#436]
Android dialogs have a setter for controlling the close behavior when a touch outside the dialog occurs. The Tabris ClientDialog API should allow to set this behavior.

Reference: https://developer.android.com/reference/android/app/Dialog.html#setCanceledOnTouchOutside(boolean)

**Comment by evolanakis** [comment]
We decided to go with the default Android behavior (close on touch outside: true). We do not need this feature right now.

**Comment by mpost** [comment]
Closing as wont fix for now.
