### ISSUE TITLE
Integrate Tabris and Tabris.js

### ISSUE THREAD

**Issue by gmitros** [eclipsesource/tabris#437]

**Comment by gosia-eclipsesource** [comment]
Tabris Remote and Tabris.js will be integrated in Q4 of this year.

**Comment by bev-on** [comment]
@gosia-eclipsesource does it means that Tabrie.js 2.0 with Windows 10 support will be released in Q4 this year? (Milestone 2.0.0)

Also can you tell us estimate date of 1.9 release?

**Comment by gosia-eclipsesource** [comment]
@bev-on Sorry I missed your message. Yes, Tabris.js 2.0 will come out together with Tabris remote in Q4. Good on you for spotting that :) But there's at least one more Tabris.js release coming up between 1.9 and 2.0.

Tabris.js 1.9 will be out in the week of July 11.

**Comment by mouaniss** [comment]
@gosia-eclipsesource Any update ?

**Comment by ifurnadjiev** [comment]
Tabris for Eclipse RAP 3.6 is based on tabris.js. It's now possible to create part of the UI in JS.
