### ISSUE TITLE
Unable to create non-debug app from phone

### ISSUE THREAD

**Issue by jandrieu** [eclipsesource/tabris#442]
There doesn't appear to be a way to create a signing key from my Android phone.  The normal way is to install Java and run keytool. But that doesn't work on my phone.  I tried looking for the android keystore in the "keystore file" part of the app settings, but couldn't find it.

Which means that, although I can create an app with debug on, I can't create one with it off.  Not until I can make it back to the office, install the JDK, and make a key there.

**Comment by mpost** [comment]
You are correct about that. At the moment the release key has to be created by you and uploaded to tabrisjs.com.
