### ISSUE TITLE
Option to disable the iOS 'clipboard' for cut/copy operations in Text widgets

### ISSUE THREAD

**Issue by evolanakis** [eclipsesource/tabris#447]
Copy / cut operations in a text control now share the selected string between devices on the same iOs account (via handoff / bluetooth). This was added with iOs 10. For sensitive apps it is desired to disable this.

https://developer.apple.com/reference/uikit/uipasteboardoptionlocalonly?language=objc

I'm adding the following new API to 1.5-maintenance:

``TextDecorator.useLocalClipboard();``

**Comment by evolanakis** [comment]
Please review commits for #447 in our gerrit (1x java, 1x iOS)

**Comment by patrykmol** [comment]
Done.

**Comment by evolanakis** [comment]
Available in 1.5-maintenance
