### ISSUE TITLE
Question: Cloud Push / FCM - working example 

### ISSUE THREAD

**Issue by camstuart** [eclipsesource/tabris#451]
What's the recommended cloud messaging approach for Tabris.

CloudPush (http://developer.eclipsesource.com/tabris/docs/2.0/working/client-services/cloud-push/)

Seems fairly involved, requiring Xcode to set up an "application delegate"

And firebase cloud messaging support was not clear (platforms, Tabris version)

In the current day, what is the recommended approach? And is there a clear example or tutorial?

**Comment by mpost** [comment]
@camstuart since you were previously commenting on tabris.js, you are referring to tabris with the server side RAP backend right now?

**Comment by camstuart** [comment]
Oh, sorry. Didn't distinguish between the two. I'll move this to tabris-js issues
