### ISSUE TITLE
Tabris 2.0.0 & 2.0.1: Refresh Content

### ISSUE THREAD

**Issue by amedavid** [eclipsesource/tabris#453]
iOS(2.0.0 & 2.0.1): The Refresh Content function do not work anymore. 
Android(2.0.0 & 2.0.1): Everthing works fine.

**Comment by patrykmol** [comment]
Hello. Can you provide a snippet or describe the scenario where this problem occurs?

**Comment by amedavid** [comment]
Hello, we sent a Mail to the tabrisadress with a Video. Did you see that?

**Comment by ifurnadjiev** [comment]
Sorry.... I missed the video attached to the mail. Is this a RefreshComposite or it is a Tree with RefreshHandler?

**Comment by amedavid** [comment]
It's a RefreshComposite

**Comment by ifurnadjiev** [comment]
Can you provide a small snippet to demonstrate the issue? What is the used iOS version?

**Comment by amedavid** [comment]
How can i send you a PM? Because of data protection i can't push the Video here. iOS-Version 10.2.1

**Comment by ifurnadjiev** [comment]
A video will not help... Please create a simple Java snippet that demonstrate the issue.

**Comment by amedavid** [comment]
`private void createRefreshingComposite(Composite parent) {
        this.refreshingComposite = new RefreshComposite(parent, SWT.NONE);
        GridLayoutFactory.fillDefaults().numColumns(1).equalWidth(false).margins(0, 0).applyTo(refreshingComposite);
        refreshingComposite.setMessage(Labels.get().TourPage_RefreshContentText);
        refreshingComposite.addRefreshListener(new RefreshListener() {
            @Override
            public void refresh() {
                businessObject.reAssignTour();
                deliveriesControl.setTour(businessObject.getTour());
                deliveriesControl.refresh();
                refreshingComposite.done();
            }
        });
    }`

**Comment by ifurnadjiev** [comment]
Thanks... we'll try to reproduce it on our side.

**Comment by patrykmol** [comment]
Fix for this will be included in next release (including message under the refresh indicator).
