### ISSUE TITLE
How to make an animation between 2 pages

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris#454]
Hello everyone please i want to know(with a snippet if it's possible) how to make a animation between two pages A et B and how to reverse the animation when the back button is pressed
Thank You

**Comment by mpost** [comment]
Hello @ishigo1987. Are you refering to tabris or tabris.js? I would assume the later. If that is the case please open your issue at https://github.com/eclipsesource/tabris-js. Thanks.

**Comment by ishigo1987** [comment]
thank you
