### ISSUE TITLE
Support for Firebase Cloud Messaging (FCM)

### ISSUE THREAD

**Issue by ericfischerrv** [eclipsesource/tabris#456]
Is Firebase Cloud Messaging supported in Tabris 2.0? The documentation has only a note on GCM, which will be deprecated in future. In Tabris.js, FCM seems to be supported.

Is there any way to upgrade to FCM by our own?

**Comment by ifurnadjiev** [comment]
CloudPush service in Tabris for Eclipse RAP 3.6 is now based on FCM.
