### ISSUE TITLE
Layout for iPhone X

### ISSUE THREAD

**Issue by mouaniss** [eclipsesource/tabris#460]
Is Tabris compatibility with iPhone X layout on the way ?

**Comment by mpost** [comment]
It will likely be compatible out of the box, but of course we will make sure you can also use it on the iPhone X.

**Comment by mouaniss** [comment]
Thank you

**Comment by amedavid** [comment]
When will tabris be compatible with the iphone x/ xs layout? We have a black bar on the top and bottom!

**Comment by ifurnadjiev** [comment]
Which Tabris for RAP version are you using? 2.0.2 or pre-released Tabris for RAP 3.5 based on tabris..js?

**Comment by amedavid** [comment]
We are using Tabris-2.0.2 for RAP

**Comment by amedavid** [comment]
@ifurnadjiev Do you have a solution for us?

**Comment by ifurnadjiev** [comment]
Tabris for Eclipse RAP 3.6 is compatible with  iPhone X.
