### ISSUE TITLE
onLabel( label ).useZoom() on Android doesn't work

### ISSUE THREAD

**Issue by KathrinKieckbusch** [eclipsesource/tabris#465]
Hi there,
we tried to implement a zooming function:

Label zoomedImageLabel = new Label(parent, SWT.NONE);
onLabel(zoomedImageLabel).useZoom();
zoomedImageLabel.setImage(image);

on iOS it works fine but on android there's no zooming behavior

**Comment by mpost** [comment]
That is correct the zooming feature is not supported on Android in Tabris 2. It will be supported in Tabris 3.
