### ISSUE TITLE
ScrollingComposite does not scroll - Tabris for RAP3.6

### ISSUE THREAD

**Issue by JohnGymer** [eclipsesource/tabris#466]
When a ScrolledComposite has content larger than the display area, it should scroll, as it did in previous Tabris versions (2.0). In browser it works OK, but on devices using the Tabris for RAP 3.6 client, it will not scroll.

Example code below:

/* DEMONSTRATES ScrolledComposite issue with Tabris for RAP 3.6 */
package bug.snippet;

import org.eclipse.swt.SWT;
import org.eclipse.swt.custom.ScrolledComposite;
import org.eclipse.swt.layout.FormAttachment;
import org.eclipse.swt.layout.FormData;
import org.eclipse.swt.layout.FormLayout;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Label;
import org.eclipse.swt.widgets.Shell;
import org.eclipse.swt.graphics.Color;
import org.eclipse.swt.graphics.RGB;

public class Bugsy {
	private Display display;
	private Shell shell;
	ScrolledComposite sComp;
	Composite comp;
	Label[] labs;
	static int labSz = 15;
	
	public void begin() {
		System.out.println("BugSnippy Starting...");

		FormData fd;
		
		display = new Display();
		shell = new Shell(display, SWT.TITLE|SWT.CLOSE|SWT.RESIZE);
		shell.setText("Shell");
		shell.setFullScreen(true);
		shell.setBackground(new Color(null, new RGB(255,192,255)));
		shell.setLayout(new FormLayout());

		sComp = new ScrolledComposite(shell, SWT.V_SCROLL|SWT.H_SCROLL);
		sComp.setBackground(new Color(null, new RGB(0,0,255)));
		sComp.setLayout(new FormLayout());
		sComp.setExpandHorizontal(true);
		sComp.setExpandVertical(true);
		sComp.setMinSize(300, (labSz*100)+20);
		fd = new FormData();
		fd.left = new FormAttachment(0, 10);
		fd.top = new FormAttachment(0, 10);
		fd.right = new FormAttachment(100, -10);
		fd.bottom = new FormAttachment(100, -10);
		sComp.setLayoutData(fd);

		comp = new Composite(sComp, SWT.NONE);
		comp.setBackground(new Color(null, new RGB(255,127,0)));
		comp.setLayout(new FormLayout());
		fd = new FormData();
		fd.left = new FormAttachment(0, 10);
		fd.top = new FormAttachment(0, 10);
		fd.right = new FormAttachment(100, -10);
		fd.bottom = new FormAttachment(100, -10);
		comp.setLayoutData(fd);

		sComp.setContent(comp);
		
		labs = new Label[labSz];
		for (int i = 0; i < labSz; i++) {
			labs[i] = new Label(comp, SWT.NONE);
			labs[i].setText("Item " + i);
			labs[i].setBackground(new Color(null, new RGB(0,127,255)));
			fd = new FormData();
			fd.left = new FormAttachment(0, 10);
			fd.top = new FormAttachment(0, 10+(i*100));
			fd.right = new FormAttachment(100, -10);
			fd.height = 80;
			labs[i].setLayoutData(fd);
		}
		
		shell.open();

		System.out.println("BugSnippy Done!");
	}
}

(same code works OK in Tabris 2.0)

**Comment by ifurnadjiev** [comment]
Please use only SWT.V_SCROLL style flag for ScrolledComposite. Putting both will assume "horizontal scrolling" only.

**Comment by JohnGymer** [comment]
This is a new restriction using JS?
Old Tabris allowed it on iOS and Android. iOS seems OK still, but not Android.
Are you saying that we cannot have ScrolledComposites that scroll both ways on Android?

**Comment by ifurnadjiev** [comment]
Yes... this is a limitation on the native client. Only scrolling in one direction is possible.

**Comment by JohnGymer** [comment]
Ok - just something we need to be aware of during app design.
thx
