### ISSUE TITLE
Windows10 Client for Tabris for RAP

### ISSUE THREAD

**Issue by JohnGymer** [eclipsesource/tabris#467]
How up to date is the Windows10 client for Tabris for RAP on the Microsoft Store?
I installed it onto a PC and it can connect OK to your demo service, but it will not talk to my local service (Android app connects OK to the same URL).

**Comment by ifurnadjiev** [comment]
Here is some information how to enable loopback addresses [1].

[1] https://docs.tabris.com/latest/windows-support.html#notes-on-windows-10-support

**Comment by JohnGymer** [comment]
Thanks Ivan, but I tried this and it didn't seem to help. I still get:
![image](https://user-images.githubusercontent.com/3033278/56723453-e475bd00-6740-11e9-84cc-e0b99cd0d607.png)

I tried the command in an Admin Command Prompt before starting anything, and also during running the appserver and the Tabris Windows client, but didn't help... any other ideas?

**Comment by tbuschto** [comment]
This is a different app from the tabris **JS** developer app, so the CheckNetIsolation command needs a different SID paramter. The SID for the Tabris/RAP app is `S-1-15-2-3043932848-1134228876-3335183018-1322036294-236893246-2099245947-2876758097`, so the command should be

```
CheckNetIsolation.exe LoopbackExempt -a -p="S-1-15-2-3043932848-1134228876-3335183018-1322036294-236893246-2099245947-2876758097"
```

**Comment by JohnGymer** [comment]
Thanks Tim - that now works OK!
...now onto testing it with Win10 for the first time!!
