### ISSUE TITLE
Supported versions of devices

### ISSUE THREAD

**Issue by JohnGymer** [eclipsesource/tabris#468]
What are the official versions of devices that will be supported by Tabris for RAP 3.6?
For example, iPad, I have iOS 12.2 working, but cannot get an older Mini on iOS 9.3.5 to connect.

**Comment by ifurnadjiev** [comment]
It's Android 4.4 and iOS 10+. Tabris for RAP 3.6 is based on tabris.js 2.7.0.

**Comment by JohnGymer** [comment]
Ok thanks.  Understood.
