### ISSUE TITLE
iOS Action Bar foreground colours

### ISSUE THREAD

**Issue by JohnGymer** [eclipsesource/tabris#469]
In Tabris for RAP 3.6, on iOS, how do I control the foreground colours of the back menu and other Action Bar items?  The page config foreground colour only seems to affect the title of the page (this is using TabrisUI), but the navigation items and actions always appear in cyan.
![iPadActionBarColours](https://user-images.githubusercontent.com/3033278/56718987-c5bef880-6737-11e9-9b04-3ba500ae3278.jpg)

UIConfiguration fg and bg colours work, but only for the bg and the title:
`			uiCfg.setBackground(main.iOSActionBarBGColour);
			uiCfg.setForeground(main.iOSActionBarFGColour);
`

**Comment by ifurnadjiev** [comment]
That's fixed in latest tabris-js-remote module - 3.6.8
