### ISSUE TITLE
iOS appserver restarted needs app kill

### ISSUE THREAD

**Issue by JohnGymer** [eclipsesource/tabris#470]
If I cycle my appserver for Tabris for RAP 3.6, any iOS client (possibly others - haven't tried yet) needs to be properly killed on the device otherwise it just comes back with a blank screen saying "Tabris.js REMOTE" and there is no way to do anything with it.

The old Tabris used to detect connection loss, issue a pop-up and allow you to restart the application.

**Comment by ifurnadjiev** [comment]
The Tabris for RAP 3.6 also detects connection lost. App server restart when the application is running invalidates the session. I need to check how it's behave in this case.

**Comment by JohnGymer** [comment]
Android seems better at handling appserver close/restart. iOS not so good.

**Comment by ifurnadjiev** [comment]
Just checked myself. On Android/Windows we have "Session timeout" dialog with an option for restart. It seems there is an issue on iOS only.

**Comment by ifurnadjiev** [comment]
That's fixed in the latest tabris-js-remote module
