### ISSUE TITLE
Tabris Canvas and drawImage issue

### ISSUE THREAD

**Issue by JohnGymer** [eclipsesource/tabris#473]
Are there any known issues with Canvas widgets in Tabris?
Many of my draw functions work OK, but as soon as I try to include a gc.drawImage call in my Canvas paint method, it hangs the Tabris client.

On Android I get a brief pop up message at the bottom, which I'm struggling to read because it doesn't stay long enough... something like:
Could not process response:
Caused by error: drawing operation failed...

In the side-swipe console I see more, but it doesn't mean much to me:
(I) could not process repsonse
Caused by Error: Drawing operation failed: [ drawImage, rwt-resources/generated/96c2d7d3.png, 0, 0 ] :Cannot read property 'apply' of undefined
at GCOperator._handleDraw(./node_modules/tabris-js-remote/dist/main.js: 2894:15)
... and a lot more output

**Comment by ifurnadjiev** [comment]
Any snippet to reproduce it?

**Comment by JohnGymer** [comment]
Snippet below..

Any image will do.  Error occurs on Android, iOS and Windows Tabris clients...


`/* DEMONSTRATES Canvas Image bug */
package bug.snippet;

import java.io.IOException;
import java.io.InputStream;

import org.eclipse.rap.rwt.RWT;
import org.eclipse.rap.rwt.service.ResourceManager;
import org.eclipse.swt.SWT;
import org.eclipse.swt.events.PaintEvent;
import org.eclipse.swt.events.PaintListener;
import org.eclipse.swt.graphics.Color;
import org.eclipse.swt.graphics.GC;
import org.eclipse.swt.graphics.Image;
import org.eclipse.swt.graphics.ImageData;
import org.eclipse.swt.graphics.Rectangle;
import org.eclipse.swt.layout.FormAttachment;
import org.eclipse.swt.layout.FormData;
import org.eclipse.swt.layout.FormLayout;
import org.eclipse.swt.widgets.Canvas;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Shell;

public class Bugsy {
	Display display;
	Shell shell;
	Canvas canv;
	Image img;
	
	public void begin() {
		System.out.println("BugSnippy Starting...");
		
		// create the Shell
		display = new Display();
		shell = new Shell(display, SWT.NONE);
		shell.setText("Shell");
		shell.setFullScreen(true);
		shell.setBackground(null); //new Color(null, new RGB(255,255,255)));
		FormLayout layout = new FormLayout();
		shell.setLayout(layout);
		FormData fd;

		img = retrieveImage("/src/pics/bike.jpg");

		canv = new Canvas(shell, SWT.BORDER);
		fd = new FormData();
		fd.left = new FormAttachment(0, 10);
		fd.top = new FormAttachment(0, 10);
		fd.right = new FormAttachment(100, -10);
		fd.bottom = new FormAttachment(100, -10);
		canv.setLayoutData(fd);
		canv.setBackground(new Color(display, 255,0,0));
		canv.addPaintListener(canvasPaintListener);

		shell.open();

		System.out.println("BugSnippy Done!");
	}

	PaintListener canvasPaintListener = new PaintListener() {
		public void paintControl(PaintEvent event) {
			doCanvPaint(event.gc, Display.getCurrent());
		}
	};

	protected void doCanvPaint(GC gc, Display dis) {
		Color cRed = new Color(null, 255, 128, 0);
		Color cBlue = new Color(null, 0, 128, 200);
		gc.setBackground(cRed);
		gc.setForeground(cBlue);
		
		gc.drawRectangle(new Rectangle(25, 25, 150, 150));
		gc.fillRectangle(new Rectangle(40, 50, 25, 40));
		
		gc.drawText("MyText", 35, 35, true);
		
		if (img != null) gc.drawImage(img, 215, 230);
	}

	private Image retrieveImage(String imageFile) {
		String imgName = imageFile;
		ResourceManager resourceManager = RWT.getResourceManager();
		Image img = null;
		if( !resourceManager.isRegistered(imgName) ) {
			InputStream inputStream = this.getClass().getClassLoader().getResourceAsStream(imgName);
			ImageData source = new ImageData(inputStream);
			img = new Image(null, source);
			try {
				inputStream.close();
			} catch (IOException e) {
				e.printStackTrace();
			}
			return(img);
		}		
		return(null);
	}

}
`

**Comment by ifurnadjiev** [comment]
It's fixed. Requires tabris.js 2.8 and tabris-js-remote 3.6.17
