### ISSUE TITLE
Android drop-downs not indicated

### ISSUE THREAD

**Issue by JohnGymer** [eclipsesource/tabris#475]
Previously on Android, a drop-list was indicated with a little corner arrow in the bottom right of the control, but there is nothing there now, so the control just looks like some read-only literal, but does respond correctly when touched.

Is there some new way to cause a drop-down (Combo control) to indicate that it is such a control visually?

**Comment by ifurnadjiev** [comment]
Combo is based on tabris.js Picker widget and it looks like on the image in the documentation [1]. Could you provide a screenshot?

[1] http://docs.tabris.com/latest/api/Picker.html#picker

**Comment by JohnGymer** [comment]
It seems that the underline and little arrow are there, but are always white, and since my background was also white, they are not visible.  If I have a non-white background then I can see them there in white.

Setting background colour of the Combo does not seem to have any effect.

However, in trying to create a snippet to show you, the snippet always works (default in black and honours any background colour I set for the Combo), so I'm totally confused as to what the difference is between the Snippet and my real application... am still investigating.  Various composites and scrolledComposite involved, so might be some inheritance thing.

**Comment by JohnGymer** [comment]
Turns out we were setting the BG colour for Combos (surprise). In old Tabris I think this actually changed the background colour, but now, BG is used to control the little arrow and underline colour, so a change in behaviour - at least we know.
