### ISSUE TITLE
BACK navigation on Android/Windows and Shells

### ISSUE THREAD

**Issue by JohnGymer** [eclipsesource/tabris#476]
In a TabrisUI application, if a pop-up shell is displayed, previously in Tabris, the BACK navigation action would close that shell, but keep the TabrisUI current page unchanged.

In RAP for Tabris, this behaviour seems to have changed that the BACK action always navigates back the current page, disposing any Shell that might have been popped-up.

I know I can add Back Navigation Listeners, but is this a deliberate change in behaviour, which means I have to recode how I did it previously?

**Comment by ifurnadjiev** [comment]
Fixed in tabris-js-remote v3.6.17-nightly.159
