### ISSUE TITLE
Menu.setLocation(...) has no effect in Tabris 2.x

### ISSUE THREAD

**Issue by mkempka** [eclipsesource/tabris#480]
Back in Tabris 1.x `Menu.setLocation(...)` would move the menu to a point on the screen. This only worked on iPad.

In Tabris 2.x this doesn’t have any effect any more. Instead the menu always shows up in the center of the display. Please restore the location behavior from Tabris 1.x, so that we can use the menu entries like this again: 
![Screen Shot 2014-12-01 at 14 52 59](https://user-images.githubusercontent.com/800490/95058750-40938d80-06f8-11eb-9198-d29dc0f5ec9c.png)

**Comment by patrykmol** [comment]
Action sheet's presenter has `sourceRect` property we could use to enable manipulation of position. Setting this will make action sheet appear somewhere around the specified `rect`. We would have to make new APIs for this.

**Comment by cpetrov** [comment]
As discussed with @ifurnadjiev: If it was Tabris 3.x (js), you could have positioned the popup according to the action's `absoluteBounds`: https://docs.tabris.com/latest/api/Widget.html#absolutebounds

However, backporting this feature to 2.x and exposing this API to Tabris might require some effort.

**Comment by patrykmol** [comment]
I have implemented undocumented property `sourceRect` on `ActionSheet`. It expects `Bounds` type https://docs.tabris.com/latest/types.html#bounds. It should be set before opening the action sheet.

Link to iOS' `sourceRect` doc: https://developer.apple.com/documentation/uikit/uipopoverpresentationcontroller/1622324-sourcerect?language=objc
