### ISSUE TITLE
Tabris 2.x: Add a way of knowing the location where the user last touched

### ISSUE THREAD

**Issue by mkempka** [eclipsesource/tabris#481]
Back when we worked with Tabris 1.x we used Display.getCursorLocation() to get the position of where a user touched last. In Tabris 2.x (iOS) this returns always { 0, 0 }.

Please add a way to know where the user last touched. This is important in conjunction with https://github.com/eclipsesource/tabris/issues/480

**Comment by ifurnadjiev** [comment]
Do you need this functionality on iOS only? @karolszafranski will implement in tabris.js 2.x a global touch listener that will set cursorLocation every time the user touches the screen.

**Comment by mkempka** [comment]
We need this solely in conjunction with #480. If we get a possibility for Android for that, too, then we also need the touch location there, too. It's not mission crucial though.
